spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitheartsdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #热部署
  thymeleaf:
    cache: false
# mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full

server:
  port: 8080
# mybatis公共插件配置
mapper:
    mappers:
        - com.ziqing.fithearts.mapper.CommonMapper
    not-empty: false
    identity: MYSQL


# mybatis分页插件配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
# 文件内外映射配置

file:
  staticAccessPath: /api/image/**  # 静态资源对外暴露的访问路径
  windowsUploadFolder: D://uploadFiles/  # windows文件上传目录
  linuxUploadFolder: /root/uploadFiles/  # linux文件上传目录



